//==============================================================================
//
//  subs.cpp
//
//  For compiling subs/* headers.  No other file should #include these
//  headers, which will cause the linker (as is intended) to omit them.
//
#include "algorithm"
#include "atomic"
#include "bitset"
#include "cctype"
#include "cmath"
#include "csetjmp"
#include "csignal"
#include "cstddef"
#include "cstdint"
#include "cstdio"
#include "cstdlib"
#include "cstring"
#include "ctime"
#include "dbghelp.h"
#include "direct.h"
#include "exception"
#include "fstream"
#include "intsafe.h"
#include "io.h"
#include "iomanip"
#include "ios"
#include "iosfwd"
#include "iostream"
#include "istream"
#include "iterator"
#include "list"
#include "map"
#include "memory"
#include "new"
#include "ostream"
#include "queue"
#include "set"
#include "sstream"
#include "stack"
#include "string"
#include "timeb.h"
#include "typeinfo"
#include "unordered_map"
#include "utility"
#include "vector"
#include "windows.h"
#include "winerror.h"
#include "winsock2.h"
#include "ws2tcpip.h"